### ISSUE TITLE
Issue Lorawan

### ISSUE THREAD

**Issue by rallep71** [PaulSchulz/esphome-lora-sx126x#6]
Updating /config/esphome/lorawan.yaml
------------------------------------------------------------

INFO ESPHome 2024.10.3
INFO Reading configuration /config/esphome/lorawan.yaml...
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1018, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 996, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 1091, in read_config
    res = load_config(command_line_substitutions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 945, in load_config
    return _load_config(command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 935, in _load_config
    return validate_config(config, command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 859, in validate_config
    result.run_validation_steps()
  File "/esphome/esphome/config.py", line 142, in run_validation_steps
    task.step.run(self)
  File "/esphome/esphome/config.py", line 317, in run
    component = get_component(self.domain)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/loader.py", line 196, in get_component
    assert "." not in domain
           ^^^^^^^^^^^^^^^^^
AssertionError
=========== [ERROR] /config/esphome/lorawan.yaml ===========

======================== [SUMMARY] ========================
  - /config/esphome/lorawan.yaml: FAILED

yaml:

esphome:
  name: lorawan-sx126x
  friendly_name: lorawan
  libraries:
     - "SPI"
     - "Ticker"
     - "SX126x-Arduino"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source:
      type: git
      url: https://github.com/PaulSchulz/esphome-lora-sx126x
      ref: main
    components: ["lorawan_sx126x"]

# Enable logging
logger:

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  
api:
  encryption:
    key: "2JYEzqRQzDRVPxFmSMFpy99eejls6IeXmH+GOEyo6Tk="

ota:
  - platform: esphome
    password: "a1038de807cc488795133cf7fcd4de32"

#
web_server:
  port: 80

#spi:
#  clk_pin: GPIO9
#  mosi_pin: GPIO10
#  miso_pin: GPIO11

#i2c:
#  - id: bus_a
#    sda: 17
#    scl: 18

# LoRaWAN Specific Oprions
# Setting these will enable the LoRaWAN radio mode
lorawan_sx126x.:

# # Interface to radio chip
#  pin_lora_reset: 12  # LoRa Reset
#  pin-lora_dio_1: 14  # LoRa DIO_1
#  pin_lora_busy:  13  # LoRa SPI Busy
#  pin_lora_nss:    8  # LoRa SPI CS (Chip Select)
#  pin_lora_sclk:   9  # LoRa SPI SCLK
#  pin_lora_miso:  11  # LoRa SPI MISO (Master In, Slave Out)
#  pin_lora_mosi:  10  # LoRa SPI MOSI (Master Out, Slave In)
#  radio_txen:     -1  # LoRa Antenna TX Enable, on some boards.
#  radio_rxen:     -1  # LoRa Antenna RX Enable, on some boards.

  region: EU868
#     # AS923
#     # AU915
#     # CN470
#     # CN779
#     # EU433
#     # EU868
#     # IN865
#     # KR920
#     # US915
#     # AS923_2
#     # AS923_3
#     # AS923_4
#     # RU864
  subchannel: 2
  device_type: CLASS_A
#     # CLASS_B
#     # CLASS_C

  authentication: OTAA
    # OTAA - Over the Air
    # ABP - Activation by Personalization

  app_eui: !secret lorawan_join_eui    # 8 bytes     
    # Also referred to as 'join_eui'

  device_eui: !secret lorawan_device_eui   # 8 bytes
    # The Device EUI is unique to the device, It can be set here, or will be set
    # using the WiFi MAC address, If it is set automatically, then this code
    # won't need to be recompiled for every device.

    # The following is used for Over The Air Authentication (OTAA)
  app_key:  !secret lorawan_app_key   # 16 bytes

#   # The following is required for Activation By Personalization (ABP) - Untested
#   nwks_key: "00000000000000000000000000000000"  # 16 bytes
#   apps_key: "00000000000000000000000000000000"  # 16 bytes
#   dev_addr: "00000000000000000000000000000000"  # 16 bytes

**Comment by PaulSchulz** [comment]
My apologies. LoRaWAN is not yet supported.

**Comment by rallep71** [comment]
OK
